[tool.black]
skip-string-normalization = true
line-length = 120
target-version = ['py38']

[tool.isort]
sections = 'FUTURE,STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER'
multi_line_output = 3
include_trailing_comma = true
force_sort_within_sections = true
line_length = 120
skip = 'mod,build'
